#Made by SplitYoSis
#Support at Discord: SplitYoSis#0001

#To call a defined component use '%{' before and '}% after the component's name.
format: "%luckperms_prefix%%{player-name}%%luckperms_suffix%&f: %message%"

#Placeholder api is applied.
chat-color: "&7"

#Components section.
#To make a new component simply copy/paste a current one and change the values.
#Make sure there aren't any name duplicates.
components:
  player-name: #This is the component's name
    display-text: "&f%player_name%"
    hover-text:
      - "&7Name: &d%player_name%"
      - "&7Balance: &d$%vault_eco_balance_formatted%"
      - ""
      - "&7&oClick to say hello!"
    #ClickEvent actions: COPY_TO_CLIPBOARD, OPEN_URL, RUN_COMMAND, SUGGEST_COMMAND
    click-event:
      action: "RUN_COMMAND"
      value: "/msg %player_name% hello"


features:
  chat-item:
    enable: true
    symbol: "[item]"
    format: "&7%amount%x&f%item%"
    hand-item-format: "&d%player%'s fist"
    hand-item-hover-text:
      - "&7Its a knuckle sandwich!"

  chat-inv:
    enable: true
    symbol: "[inv]"
    format: "&d%player%'s inventory"
    inventory-title: "&d%player%'s inventory"
    inventory-expire-time: 1800 #Seconds
    inventory-expired-message:
      - "&cThis inventory snapshot has expired."
    hover-text:
      - "&7Click to view the snapshot"